### ISSUE TITLE
Incompatibility with long chain upgrades

### ISSUE THREAD

**Issue by Liver-23** [KYVENetwork/supervysor#4]
### Issue description
`[supervysor] failed to query height.` - 10 retries and restart... 

This functionality is not compatible with chain upgrades when it can take time to migrate/upgrade
Playing with Osmo v6.4.0 upgrade, and after restart migration continues from the same step but if it is not completed this will be an endless loop

### Workaround: 
- manual restart without supervysor
- wait for the chain upgrade
- restart with supervysor

### Logs
```shell
12:17AM INF indexed block height=2383299 module=txindex
12:17AM ERR UPGRADE "v5" NEEDED at height: 2383300: https://raw.githubusercontent.com/osmosis-labs/osmosis/v5.x/networks/osmosis-1/upgrades/v5/mainnet/v5.0.0-binaries.json
panic: UPGRADE "v5" NEEDED at height: 2383300: https://raw.githubusercontent.com/osmosis-labs/osmosis/v5.x/networks/osmosis-1/upgrades/v5/mainnet/v5.0.0-binaries.json
goroutine 77 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{_, _}, _, {_, _}, {_, _}, _}, {{0x20796f8, 0xc000044060}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.42.9/x/upgrade/abci.go:70 +0xf08
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
        github.com/cosmos/cosmos-sdk@v0.42.9/x/upgrade/module.go:127
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x20796f8, 0xc000044060}, {0x20866c8, 0xc01ed2e800}, {{0xb, 0x1}, {0xc013760a44, 0x9}, 0x245dc4, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.42.9/types/module/module.go:341 +0x198
github.com/osmosis-labs/osmosis/app.(*OsmosisApp).BeginBlocker(_, {{0x20796f8, 0xc000044060}, {0x20866c8, 0xc01ed2e800}, {{0xb, 0x1}, {0xc013760a44, 0x9}, 0x245dc4, ...}, ...}, ...)
        github.com/osmosis-labs/osmosis/app/app.go:589 +0xdb
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc023199720, 0x20, 0x20}, {{0xb, 0x1}, {0xc013760a44, 0x9}, 0x245dc4, {0x31a65e1c, ...}, ...}, ...})
        github.com/cosmos/cosmos-sdk@v0.42.9/baseapp/abci.go:191 +0x89b
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc023199720, 0x20, 0x20}, {{0xb, 0x1}, {0xc013760a44, 0x9}, 0x245dc4, {0x31a65e1c, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc023199720, 0x20, 0x20}, {{0xb, 0x1}, {0xc013760a44, 0x9}, 0x245dc4, {0x31a65e1c, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x207a338?, 0xc007b4c480}, {0x2080410, 0xc000d58b90}, 0xc006573a40, {0x2086938, 0xc0059984c0}, 0x245dc3?)
        github.com/tendermint/tendermint@v0.34.14/state/execution.go:307 +0x51d
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc0082b0ef0, 0x7}}, {0xc0082b0ef7, 0x9}, 0x1, 0x245dc3, {{0xc011b08920, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.14/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc005b66a80, 0x0)
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:398 +0xb5a
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x7a
12:17AM INF daemon shutting down in an attempt to restart module=cosmovisor
12:17AM INF pre-upgrade command does not exist. continuing the upgrade. module=cosmovisor
12:17AM INF upgrade detected, relaunching app=osmosisd module=cosmovisor
12:17AM INF running app args=["start","--p2p.seeds","400f3d9e30b69e78a7fb891f60d76fa3c73f0ecc@osmosis.rpc.kjnodes.com:12959,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:12556","--home","/home/cosmos/.osmosisd","--x-crisis-skip-assert-invariants"] module=cosmovisor path=/home/cosmos/.osmosisd/cosmovisor/upgrades/v5/bin/osmosisd
12:17AM INF starting ABCI with Tendermint
12:17AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B3234302031303720373420313620313838203133372031372031373620343020323236203533203138362034203134322032303220313436203133352031333620323238203131362034342034302031303020313233203234392033322034302032203134312032303520313237203139325D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc000f34b80, acc}" version=0
12:17AM ERR [supervysor] failed to query height. Try again in 20s ... (1/10)
12:17AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000f34d80, authz}" version=2383300
12:17AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B31373920313134203336203230392037302031383420343520393420313035203132392039332034372034342033392031323220313039203131203137362031362032303720323336203231312031352032353520383320313237203230332032343820373520313834203731203136315D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc000f34ba0, bank}" version=0
12:17AM ERR [supervysor] failed to query height. Try again in 20s ... (2/10)
12:18AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc000f34db0, bech32ibc}" version=2383300
12:18AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B3134372032313420313734203231392031372032313520313630203134342038312036332039362031313020323331203431203138312035382032303020333420313230203133312031363420313637203131382031323520323920323032203231362031343120393720323037203138203234315D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc000f34ce0, capability}" version=0
12:18AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B3233312037332031353720313637203234372031383920313137203532203136302032362031383820353520393720363720323533203630203734203233392032313620313020323334203120323335203131203530203130203230372031373620392031322039362032395D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc000f34d20, claim}" version=0
12:18AM ERR [supervysor] failed to query height. Try again in 20s ... (3/10)
12:18AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B313135203737203135342032333220333720313230203135352031373520323237203239203233352032343020363520313438203135302031323420313420313536203830203134302039322031393720313630203231312031333320393420313331203234382031353520323030203139312037305D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc000f34be0, distribution}" version=0
12:18AM ERR [supervysor] failed to query height. Try again in 20s ... (4/10)
12:18AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B3231352031393720313420343720323236203130392039392031383620323433203620313432203233362031323820323434203230322031393120313537203020323038203834203231382032303620353320393920323039203237203134203231382031313820313533203231382034325D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc000f34d50, epochs}" version=0
12:18AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B3232372031373620313936203636203135322032353220323820323020313534203235312032343420323030203135332031313120313835203336203339203137342036352032323820313030203135352031343720373620313634203134392031353320323720313230203832203138342038355D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc000f34cb0, evidence}" version=0
12:18AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B38362032333520323720323438203230372032343120323535203133342031352035332034382031323020313037203836203234302036392033312034382031353920332031383920393020313835203137352031363220333220323337203635203233302032313720313531203131355D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc000f34cf0, gamm}" version=0
12:18AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B31372031303120323439203920313633203233312031303520313533203130382034332031393720313333203631203339203234203332203137312032343620313732203230312032313220323133203132332032343420313938203839203139342032303920322032313820323339203130305D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc000f34c40, gov}" version=0
12:18AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B31353720313332203930203634203134382033322031323820383520373620353720313120393120323430203139352032323320333720313436203234322032322033362036302031382032313320343320313236203135322038312034332039362034302033312034355D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc000f34c70, ibc}" version=0
12:18AM ERR [supervysor] failed to query height. Try again in 20s ... (5/10)
12:19AM ERR [supervysor] failed to query height. Try again in 20s ... (6/10)
12:19AM ERR [supervysor] failed to query height. Try again in 20s ... (7/10)
12:19AM ERR [supervysor] failed to query height. Try again in 20s ... (8/10)
12:20AM ERR [supervysor] failed to query height. Try again in 20s ... (9/10)
12:20AM ERR [supervysor] failed to query height. Try again in 20s ... (10/10)
12:20AM ERR [supervysor] could not get node height err="could not get node height, exiting ..."
12:20AM FTL terminated error="os: process already finished" bin=/home/cosmos/.osmosisd/cosmovisor/upgrades/v4/bin/osmosisd module=cosmovisor
Error: could not get node height, exiting ...
Usage:
  supervysor start [flags]
Flags:
  -h, --help   help for start
osmosisd.service: Main process exited, code=exited, status=1/FAILURE
osmosisd.service: Failed with result 'exit-code'.
osmosisd.service: Consumed 7h 10min 20.316s CPU time.
osmosisd.service: Scheduled restart job, restart counter is at 1.
Stopped osmosisd node service.
osmosisd.service: Consumed 7h 10min 20.316s CPU time.
Started osmosisd node service.
12:21AM INF [supervysor] starting initially
12:21AM INF [supervysor] initial process started pId=4120044
12:21AM ERR [supervysor] failed to query height. Try again in 20s ... (1/10)
12:21AM INF running app args=["start","--p2p.seeds","400f3d9e30b69e78a7fb891f60d76fa3c73f0ecc@osmosis.rpc.kjnodes.com:12959,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:12556","--home","/home/cosmos/.osmosisd","--x-crisis-skip-assert-invariants"] module=cosmovisor path=/home/cosmos/.osmosisd/cosmovisor/upgrades/v5/bin/osmosisd
12:21AM INF starting ABCI with Tendermint
12:21AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B31353720313332203930203634203134382033322031323820383520373620353720313120393120323430203139352032323320333720313436203234322032322033362036302031382032313320343320313236203135322038312034332039362034302033312034355D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc00179c680, ibc}" version=0
12:21AM ERR [supervysor] failed to query height. Try again in 20s ... (2/10)
12:22AM ERR [supervysor] failed to query height. Try again in 20s ... (3/10)
12:22AM ERR [supervysor] failed to query height. Try again in 20s ... (4/10)
12:22AM ERR [supervysor] failed to query height. Try again in 20s ... (5/10)
12:23AM ERR [supervysor] failed to query height. Try again in 20s ... (6/10)
12:23AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B3432203436203639203133392036322031323920313037203335203131392036352033332039372031303720313620313930203530203231322032323420313036203232342033332033362031333620323620313937203132382031303620323233203137382031313720323134203134365D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc00179c700, incentives}" version=0
12:23AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B3232312032313420313230203331203232372031343120323336203137302033382031333020313633203537203236203230312032313420333020313020323134203231352031353720313039203235302035342032313920323131203131362032323820353020323238203220323335203137385D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc00179c6e0, lockup}" version=0
12:23AM ERR [supervysor] failed to query height. Try again in 20s ... (7/10)
12:23AM ERR [supervysor] failed to query height. Try again in 20s ... (8/10)
12:24AM ERR [supervysor] failed to query height. Try again in 20s ... (9/10)
12:24AM ERR [supervysor] failed to query height. Try again in 20s ... (10/10)
12:24AM ERR [supervysor] could not get node height err="could not get node height, exiting ..."
Error: signal: terminated
12:24AM ERR error="signal: terminated" module=cosmovisor
Error: could not get node height, exiting ...
Usage:
  supervysor start [flags]
Flags:
  -h, --help   help for start
osmosisd.service: Main process exited, code=exited, status=1/FAILURE
osmosisd.service: Failed with result 'exit-code'.
osmosisd.service: Consumed 5min 17.210s CPU time.
osmosisd.service: Scheduled restart job, restart counter is at 2.
Stopped osmosisd node service.
osmosisd.service: Consumed 5min 17.210s CPU time.
Started osmosisd node service.
12:25AM INF [supervysor] starting initially
12:25AM INF [supervysor] initial process started pId=4134856
12:25AM ERR [supervysor] failed to query height. Try again in 20s ... (1/10)
12:25AM INF running app args=["start","--p2p.seeds","400f3d9e30b69e78a7fb891f60d76fa3c73f0ecc@osmosis.rpc.kjnodes.com:12959,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:12556","--home","/home/cosmos/.osmosisd","--x-crisis-skip-assert-invariants"] module=cosmovisor path=/home/cosmos/.osmosisd/cosmovisor/upgrades/v5/bin/osmosisd
12:25AM INF starting ABCI with Tendermint
12:25AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B3232312032313420313230203331203232372031343120323336203137302033382031333020313633203537203236203230312032313420333020313020323134203231352031353720313039203235302035342032313920323131203131362032323820353020323238203220323335203137385D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc001610420, lockup}" version=0
12:25AM ERR [supervysor] failed to query height. Try again in 20s ... (2/10)
12:25AM ERR [supervysor] failed to query height. Try again in 20s ... (3/10)
12:26AM ERR [supervysor] failed to query height. Try again in 20s ... (4/10)
12:26AM ERR [supervysor] failed to query height. Try again in 20s ... (5/10)
12:26AM ERR [supervysor] failed to query height. Try again in 20s ... (6/10)
12:27AM ERR [supervysor] failed to query height. Try again in 20s ... (7/10)
12:27AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B3136382031383220363720343620383520313934203134392033332031353620323033203534203135382032333120313535203232312032323320323030203232332038352032313720313032203139312031343720343620353220313530203135352038362032343020313532203932203135345D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc001610370, mint}" version=0
12:27AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B31303220323335203230332032333520362031323320333420313738203234362031373220313932203731203535203138392034312031343920313230203934203132392031373220383620323031203934203233332033392033342032333820333420323035203420313133203230355D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc0016103b0, params}" version=0
12:27AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B32303620313330203831203631203938203139362037342038322031333920373420333520323034203130312039322032323520313431203231322037352032343120333220393920313334203735203130302032313620313638203134372032333420313020313831203131392036325D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc001610460, poolincentives}" version=0
12:27AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B32343920313238203933203939203138312032343320313433203135203933203134362032333920343720323433203136362036382031323620313639203637203135302032303620313720353120323530203232352032322031343720323020313335203139302035203138302032315D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc001610390, slashing}" version=0
12:27AM ERR [supervysor] failed to query height. Try again in 20s ... (8/10)
12:27AM ERR [supervysor] failed to query height. Try again in 20s ... (9/10)
12:28AM ERR [supervysor] failed to query height. Try again in 20s ... (10/10)
12:28AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B32303420323036203531203230332037203137362032313220363420393120322031343820313334203339203135352038372031313120353320313037203130342032323220323237203635203137352031393820323238203137312032323920383920323333203234312033352033375D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc001610360, staking}" version=0
12:28AM ERR [supervysor] could not get node height err="could not get node height, exiting ..."
Error: signal: terminated
12:28AM ERR error="signal: terminated" module=cosmovisor
Error: could not get node height, exiting ...
Usage:
  supervysor start [flags]
Flags:
  -h, --help   help for start
osmosisd.service: Main process exited, code=exited, status=1/FAILURE
osmosisd.service: Failed with result 'exit-code'.
osmosisd.service: Consumed 5min 2.637s CPU time.
osmosisd.service: Scheduled restart job, restart counter is at 3.
Stopped osmosisd node service.
osmosisd.service: Consumed 5min 2.637s CPU time.
Started osmosisd node service.
12:29AM INF [supervysor] starting initially
12:29AM INF [supervysor] initial process started pId=4150398
12:29AM ERR [supervysor] failed to query height. Try again in 20s ... (1/10)
12:29AM INF running app args=["start","--p2p.seeds","400f3d9e30b69e78a7fb891f60d76fa3c73f0ecc@osmosis.rpc.kjnodes.com:12959,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:12556","--home","/home/cosmos/.osmosisd","--x-crisis-skip-assert-invariants"] module=cosmovisor path=/home/cosmos/.osmosisd/cosmovisor/upgrades/v5/bin/osmosisd
12:29AM INF starting ABCI with Tendermint
12:29AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B32303420323036203531203230332037203137362032313220363420393120322031343820313334203339203135352038372031313120353320313037203130342032323220323237203635203137352031393820323238203137312032323920383920323333203234312033352033375D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc001434650, staking}" version=0
12:29AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B31353320363220313835203233342031393220393920373320313930203139302033372038362031383920323335203139312031383520313031203931203139302031353820313320313438203232392031323520343420313536203232203138342034203337203235322035372036385D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc0014346e0, transfer}" version=0
12:29AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false store_key="KVStoreKey{0xc001434770, txfees}" version=2383300
12:29AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B323435203720313133203938203136302036392036312031343620323337203238203530203139392031363120313237203538203632203333203737203135332031393520313434203131203930203636203139322038382032323420363520313937203630203433203231395D3A3234354443337D is_lazy=false store_key="KVStoreKey{0xc0014346c0, upgrade}" version=0
12:29AM INF Starting multiAppConn service impl=multiAppConn module=proxy
12:29AM INF Starting localClient service connection=query impl=localClient module=abci-client
12:29AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
12:29AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
12:29AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
12:29AM INF Starting EventBus service impl=EventBus module=events
12:29AM INF Starting PubSub service impl=PubSub module=pubsub
12:29AM INF Starting IndexerService service impl=IndexerService module=txindex
12:29AM INF ABCI Handshake App Info hash="Z\x11M��4\x01�����\x14L���2�\a�O��\x1e���\n�ٟ" height=2383299 module=consensus protocol-version=0 software-version=6.4.0
12:29AM INF ABCI Replay Blocks appHeight=2383299 module=consensus stateHeight=2383299 storeHeight=2383300
12:29AM INF Replay last block using real app module=consensus
12:29AM INF applying upgrade "v5" at height: 2383300
12:29AM INF Start running migrations
12:29AM INF Running migration for module: authz, InitGenesis (on default genesis) toVersion 1
12:29AM INF Running migration for module: bank, fromVersion 1, toVersion 2
12:29AM ERR [supervysor] failed to query height. Try again in 20s ... (2/10)
12:29AM INF Running migration for module: bech32ibc, InitGenesis (on default genesis) toVersion 1
12:29AM INF Running migration for module: distribution, fromVersion 1, toVersion 2
12:29AM INF Running migration for module: gov, fromVersion 1, toVersion 2
12:29AM INF Running migration for module: ibc, fromVersion 1, toVersion 2
12:29AM ERR [supervysor] failed to query height. Try again in 20s ... (3/10)
12:30AM INF Running migration for module: slashing, fromVersion 1, toVersion 2
12:30AM ERR [supervysor] failed to query height. Try again in 20s ... (4/10)
12:30AM INF Running migration for module: staking, fromVersion 1, toVersion 2
12:30AM INF Setting txfees module genesis with actual v5 desired genesis
12:30AM INF Now running migrations just for auth, to get auth migration to be last. (CC https://github.com/cosmos/cosmos-sdk/issues/10591)
12:30AM INF Start running migrations
12:30AM INF Running migration for module: auth, fromVersion 1, toVersion 2
12:30AM INF executed block height=2383300 module=consensus num_invalid_txs=17 num_valid_txs=0
12:30AM ERR [supervysor] failed to query height. Try again in 20s ... (5/10)
12:30AM ERR [supervysor] failed to query height. Try again in 20s ... (6/10)
12:31AM ERR [supervysor] failed to query height. Try again in 20s ... (7/10)
12:31AM ERR [supervysor] failed to query height. Try again in 20s ... (8/10)
12:31AM ERR [supervysor] failed to query height. Try again in 20s ... (9/10)
12:32AM ERR [supervysor] failed to query height. Try again in 20s ... (10/10)
12:32AM ERR [supervysor] could not get node height err="could not get node height, exiting ..."
Error: signal: terminated
12:32AM ERR error="signal: terminated" module=cosmovisor
Error: could not get node height, exiting ...
Usage:
  supervysor start [flags]
Flags:
  -h, --help   help for start
osmosisd.service: Main process exited, code=exited, status=1/FAILURE
osmosisd.service: Failed with result 'exit-code'.
osmosisd.service: Consumed 5min 58.721s CPU time.
osmosisd.service: Scheduled restart job, restart counter is at 4.
Stopped osmosisd node service.
osmosisd.service: Consumed 5min 58.721s CPU time.
Started osmosisd node service.
12:32AM INF [supervysor] starting initially
12:32AM INF [supervysor] initial process started pId=4165552
12:32AM ERR [supervysor] failed to query height. Try again in 20s ... (1/10)
12:32AM INF running app args=["start","--p2p.seeds","400f3d9e30b69e78a7fb891f60d76fa3c73f0ecc@osmosis.rpc.kjnodes.com:12959,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:12556","--home","/home/cosmos/.osmosisd","--x-crisis-skip-assert-invariants"] module=cosmovisor path=/home/cosmos/.osmosisd/cosmovisor/upgrades/v5/bin/osmosisd
12:32AM INF starting ABCI with Tendermint
12:32AM INF Starting multiAppConn service impl=multiAppConn module=proxy
12:32AM INF Starting localClient service connection=query impl=localClient module=abci-client
12:32AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
12:32AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
12:32AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
12:32AM INF Starting EventBus service impl=EventBus module=events
12:32AM INF Starting PubSub service impl=PubSub module=pubsub
12:32AM INF Starting IndexerService service impl=IndexerService module=txindex
12:32AM INF ABCI Handshake App Info hash="Z\x11M��4\x01�����\x14L���2�\a�O��\x1e���\n�ٟ" height=2383299 module=consensus protocol-version=0 software-version=6.4.0
12:32AM INF ABCI Replay Blocks appHeight=2383299 module=consensus stateHeight=2383299 storeHeight=2383300
12:32AM INF Replay last block using real app module=consensus
12:32AM INF applying upgrade "v5" at height: 2383300
12:32AM INF Start running migrations
12:32AM INF Running migration for module: authz, InitGenesis (on default genesis) toVersion 1
12:32AM INF Running migration for module: bank, fromVersion 1, toVersion 2
12:33AM INF Running migration for module: bech32ibc, InitGenesis (on default genesis) toVersion 1
12:33AM INF Running migration for module: distribution, fromVersion 1, toVersion 2
12:33AM INF Running migration for module: gov, fromVersion 1, toVersion 2
12:33AM INF Running migration for module: ibc, fromVersion 1, toVersion 2
12:33AM ERR [supervysor] failed to query height. Try again in 20s ... (2/10)
12:33AM ERR [supervysor] failed to query height. Try again in 20s ... (3/10)
12:33AM INF Running migration for module: slashing, fromVersion 1, toVersion 2
12:33AM INF Running migration for module: staking, fromVersion 1, toVersion 2
12:33AM INF Setting txfees module genesis with actual v5 desired genesis
12:33AM INF Now running migrations just for auth, to get auth migration to be last. (CC https://github.com/cosmos/cosmos-sdk/issues/10591)
12:33AM INF Start running migrations
12:33AM INF Running migration for module: auth, fromVersion 1, toVersion 2
12:33AM INF executed block height=2383300 module=consensus num_invalid_txs=17 num_valid_txs=0
12:33AM ERR [supervysor] failed to query height. Try again in 20s ... (4/10)
12:34AM ERR [supervysor] failed to query height. Try again in 20s ... (5/10)
12:34AM ERR [supervysor] failed to query height. Try again in 20s ... (6/10)
12:34AM ERR [supervysor] failed to query height. Try again in 20s ... (7/10)
12:35AM ERR [supervysor] failed to query height. Try again in 20s ... (8/10)
12:35AM ERR [supervysor] failed to query height. Try again in 20s ... (9/10)
12:35AM ERR [supervysor] failed to query height. Try again in 20s ... (10/10)
12:36AM ERR [supervysor] could not get node height err="could not get node height, exiting ..."
Error: signal: terminated
12:36AM ERR error="signal: terminated" module=cosmovisor
Error: could not get node height, exiting ...
Usage:
  supervysor start [flags]
Flags:
  -h, --help   help for start
osmosisd.service: Main process exited, code=exited, status=1/FAILURE
osmosisd.service: Failed with result 'exit-code'.
osmosisd.service: Consumed 6min 27.139s CPU time.
osmosisd.service: Scheduled restart job, restart counter is at 5.
Stopped osmosisd node service.
osmosisd.service: Consumed 6min 27.139s CPU time.
Started osmosisd node service.
12:36AM INF [supervysor] starting initially
12:36AM INF [supervysor] initial process started pId=4180880
12:36AM ERR [supervysor] failed to query height. Try again in 20s ... (1/10)
12:36AM INF running app args=["start","--p2p.seeds","400f3d9e30b69e78a7fb891f60d76fa3c73f0ecc@osmosis.rpc.kjnodes.com:12959,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:12556","--home","/home/cosmos/.osmosisd","--x-crisis-skip-assert-invariants"] module=cosmovisor path=/home/cosmos/.osmosisd/cosmovisor/upgrades/v5/bin/osmosisd
12:36AM INF starting ABCI with Tendermint
12:36AM INF Starting multiAppConn service impl=multiAppConn module=proxy
12:36AM INF Starting localClient service connection=query impl=localClient module=abci-client
12:36AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
12:36AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
12:36AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
12:36AM INF Starting EventBus service impl=EventBus module=events
12:36AM INF Starting PubSub service impl=PubSub module=pubsub
12:36AM INF Starting IndexerService service impl=IndexerService module=txindex
12:36AM INF ABCI Handshake App Info hash="Z\x11M��4\x01�����\x14L���2�\a�O��\x1e���\n�ٟ" height=2383299 module=consensus protocol-version=0 software-version=6.4.0
12:36AM INF ABCI Replay Blocks appHeight=2383299 module=consensus stateHeight=2383299 storeHeight=2383300
12:36AM INF Replay last block using real app module=consensus
12:36AM INF applying upgrade "v5" at height: 2383300
12:36AM INF Start running migrations
12:36AM INF Running migration for module: authz, InitGenesis (on default genesis) toVersion 1
12:36AM INF Running migration for module: bank, fromVersion 1, toVersion 2
12:36AM INF Running migration for module: bech32ibc, InitGenesis (on default genesis) toVersion 1
12:36AM INF Running migration for module: distribution, fromVersion 1, toVersion 2
12:36AM INF Running migration for module: gov, fromVersion 1, toVersion 2
12:36AM INF Running migration for module: ibc, fromVersion 1, toVersion 2
12:37AM ERR [supervysor] failed to query height. Try again in 20s ... (2/10)
12:37AM INF Running migration for module: slashing, fromVersion 1, toVersion 2
12:37AM ERR [supervysor] failed to query height. Try again in 20s ... (3/10)
12:37AM INF Running migration for module: staking, fromVersion 1, toVersion 2
12:37AM INF Setting txfees module genesis with actual v5 desired genesis
12:37AM INF Now running migrations just for auth, to get auth migration to be last. (CC https://github.com/cosmos/cosmos-sdk/issues/10591)
12:37AM INF Start running migrations
12:37AM INF Running migration for module: auth, fromVersion 1, toVersion 2
12:37AM INF executed block height=2383300 module=consensus num_invalid_txs=17 num_valid_txs=0
12:37AM ERR [supervysor] failed to query height. Try again in 20s ... (4/10)
12:38AM ERR [supervysor] failed to query height. Try again in 20s ... (5/10)
12:38AM ERR [supervysor] failed to query height. Try again in 20s ... (6/10)
```

**Comment by Liver-23** [comment]
### Thoughts about solution
- gather data from the targeted chain with the list of upgrade blocks: even if not possible to parse then just create a manual config file with map of upgrades
- update halt-height to "upgrade block - N" value
- once halt height is reached turn off reboot functionality and wait until "upgrade block + N"
- when "upgrade block + N" is reached turn the reboot on again
- update halt-height to the next value if exists

**Comment by christopherbrumm** [comment]
With #5, this will be resolved due to the exponential backoff. Due to the longer timeframe, nodes will have the chance to perform big upgrades when running with the Cosmovisor.

However, can you explain how you did end up in an endless loop?

**Comment by Liver-23** [comment]
After each 10 retires the node was restarted and once up it is trying to migrate again and again, and the time dedicated to 10 retries is not enough.
As I understand `12:37AM INF executed block height=2383300 module=consensus num_invalid_txs=17 num_valid_txs=0` such 1st block after the upgrade can take much more time to be processed

**Comment by christopherbrumm** [comment]
This behaviour should be prevented by a longer upgrade timeframe.

Due to the potential big timeframe, I will increase the `BackoffMaxRetries` to 15 ([commit](https://github.com/KYVENetwork/supervysor/pull/5/commits/b9d83032d9ad7def4f30158c0480bc49f0c46c1e)) so the node has more than 16 hours to upgrade successfully before the supervysor exits.
